.apex/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Family0</fullName>
                </value>
                <value>
                    <fullName>Family1</fullName>
                </value>
                <value>
                    <fullName>Family2</fullName>
                </value>
                <value>
                    <fullName>Family3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type0</fullName>
                </value>
                <value>
                    <fullName>Type1</fullName>
                </value>
                <value>
                    <fullName>Type2</fullName>
                </value>
                <value>
                    <fullName>Type3</fullName>
                </value>
                <value>
                    <fullName>Type4</fullName>
                </value>
                <value>
                    <fullName>Type5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>isManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isManager</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

.apex/src/classes/TestItemsTrigger.cls
@IsTest
private class TestItemsTrigger {
	@testSetup
	static void createOrder() {
		Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];

		List<User> users = new List<User>{
				new User(
						LastName = 'LIVESTON',
						FirstName = 'JASON',
						Email = 'jason.liveston@asdf.com',
						Username = 'jason.liveston@truesalessoft.com',
						ProfileId = profileId.id,
						Alias = 'alias',
						TimeZoneSidKey = 'America/Los_Angeles',
						LocaleSidKey = 'en_US',
						EmailEncodingKey = 'UTF-8',
						LanguageLocaleKey = 'en_US',
						isManager__c = false
				)};
		insert users;

		List<Account> accounts = new List<Account>{
				new Account(
						Name = 'TestAccount1',
						AccountNumber = 'TT000000',
						OwnerId = users[0].Id
				)};
		insert accounts;

		List<Product__c> products = new List<Product__c> {
				new Product__c(
						Name = 'Test Product 2',
						Price__c = 10,
						Family__c = 'Family1',
						Type__c = 'Type0'
				),
				new Product__c(
						Name = 'Test Product 3',
						Price__c = 100,
						Family__c = 'Family1',
						Type__c = 'Type2'
				)};
		insert products;

		List<Order__c> orders = new List<Order__c>{
				new Order__c(
						Name = 'Test Order 1',
						AccountId__c = accounts[0].Id,
						TotalProductCount__c = 0,
						TotalPrice__c = 0
				)};
		insert orders;

		List<OrderItem__c> orderItems = new List<OrderItem__c>{
				new OrderItem__c(
						Name = 'Test Order Item 1',
						ProductId__c = products[0].Id,
						OrderId__c = orders[0].Id,
						Quantity__c = 5
				),
				new OrderItem__c(
						Name = 'Test Order Item 2',
						ProductId__c = products[1].Id,
						OrderId__c = orders[0].Id,
						Quantity__c = 8
				)};
		insert orderItems;
	}

	@isTest
	static void testOrderTrigger() {
		Order__c order = [SELECT TotalPrice__c, TotalProductCount__c from Order__c limit 1];
		System.assertEquals(order.TotalPrice__c, 850);
		System.assertEquals(order.TotalProductCount__c, 13);
	}
}