.apex/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Family0</fullName>
                </value>
                <value>
                    <fullName>Family1</fullName>
                </value>
                <value>
                    <fullName>Family2</fullName>
                </value>
                <value>
                    <fullName>Family3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type0</fullName>
                </value>
                <value>
                    <fullName>Type1</fullName>
                </value>
                <value>
                    <fullName>Type2</fullName>
                </value>
                <value>
                    <fullName>Type3</fullName>
                </value>
                <value>
                    <fullName>Type4</fullName>
                </value>
                <value>
                    <fullName>Type5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/classes/FilterProductsController.cls
public class FilterProductsController {
	@AuraEnabled(cacheable=true)
	public static List<String> getFamilies() {
		List<String> result = new List<String>{};
		Set<String> families = new Set<String>{};

		for (Product__c prod :[
				SELECT Family__c
				from Product__c
		]) {
			families.add(prod.Family__c);
		}
		result.addAll(families);
		result.sort();
		return result;
	}

	@AuraEnabled(cacheable=true)
	public static List<String> getTypes() {
		List<String> result = new List<String>{};
		Set<String> types = new Set<String>{};

		for (Product__c prod :[
				SELECT Type__c
				from Product__c
		]) {
			types.add(prod.Type__c);
		}
		result.addAll(types);
		result.sort();
		return result;
	}

	@AuraEnabled(cacheable=true)
	public static List<Product__c> filerResult(String[] familyFilters, String[] typeFilters, String searchKey) {
		if (familyFilters == null && typeFilters == null && searchKey == null)
			return ([SELECT Name, Description__c,Image__c FROM Product__c]);

		List<String> criteria = new List<String>{};
		String whereClause = '';
		String newSearchKey = '%' + searchKey + '%';

		if (familyFilters != null && familyFilters.size() != 0) {
			criteria.add('Family__c IN :familyFilters');
		}
		if (typeFilters != null && typeFilters.size() != 0) {
			criteria.add('Type__c in :typeFilters');
		}
		if (searchKey != null && searchKey.length() != 0) {
			criteria.add('Name LIKE :newSearchKey');
		}
		if (criteria.size() > 0) {
			whereClause = 'WHERE ' + String.join(criteria, ' AND ');
		}

		return Database.query(
						'SELECT Name, Description__c,Image__c FROM Product__c ' + whereClause
		);
	}
}